name: enigma_dart
repository: https://github.com/gedzeppelin/enigma_dart
description: A collection of widgets and utilities following the EnigmaUI conventions.
version: 0.0.1
#author: Gedy Palomino <gedy.palomino@gmail.com>

environment:  
  sdk: ">=2.7.0 <3.0.0" 

dependencies:  
  # Flutter SDK.
  flutter:
    sdk: flutter
  
  # Package dependencies.
  connectivity: "^2.0.0"
  dartz: ">=0.9.2 <1.0.0"
  flutter_spinkit: ">=4.1.2+1 <5.0.0"
  http: ">=0.12.2 <1.0.0"
  
  # Annotations for EnigmaUI.
  enigma_annotation: ">=0.0.1 <0.0.2"

dev_dependencies:
  # Flutter test SDK.
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#dependency_overrides:
#  enigma_annotation:
#    path: ../enigma_annotation