name: enigma_dart
repository: https://github.com/gedzeppelin/enigma_dart
description: A collection of widgets and utilities following the EnigmaUI conventions.
version: 0.1.0
#author: Gedy Palomino <gedy.palomino@gmail.com>

environment:  
  sdk: ">=2.12.0 <3.0.0" 

dependencies:  
  # Flutter SDK.
  flutter:
    sdk: flutter
  
  # Package dependencies.
  connectivity: ^3.0.0
  flutter_spinkit: ^5.0.0
  flutter_staggered_grid_view: ">=0.4.0 <1.0.0"
  http: ">=0.13.3 <1.0.0"

  # Annotations for EnigmaUI.
  enigma_annotation: 0.1.0
  # Enigma dart core.
  enigma_core: 0.1.0  
  

dev_dependencies:
  # Flutter test SDK.
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  enigma_annotation:
    path: ../enigma_annotation
  enigma_core:
    path: ../enigma_core