name: enigma_core
repository: https://github.com/gedzeppelin/enigma_dart
description: Enigma framework core dart package.
version: 0.1.0

environment:  
  sdk: ">=2.12.0 <3.0.0" 

dependencies:  
  # Flutter SDK.
  flutter:
    sdk: flutter
  
  # Package dependencies.
  connectivity: "^3.0.0"
  http: ">=0.13.3 <1.0.0"
  
  # Annotations for EnigmaUI.
  enigma_annotation: 0.1.0

dev_dependencies:
  # Flutter test SDK.
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  enigma_annotation:
    path: ../enigma_annotation