name: pagination_generator
description: An annotation processor for @Paginated annotations.
version: 1.0.0
author: Gedy Palomino <gedy.palomino@gmail.com>

environment:  
  sdk: ">=2.0.0 <3.0.0" 

dependencies:  
  meta: ^1.1.0
  build: ^1.0.0
  source_gen: ^0.9.0