name: enigma_serializable
repository: https://github.com/gedzeppelin/enigma_dart
description: Automatically generate code for EnigmaUI conventions by annotating Dart classes.
version: 0.1.0
#author: Gedy Palomino <gedy.palomino@gmail.com>

environment:  
  sdk: ">=2.12.0 <3.0.0" 

dependencies:  
  analyzer: ^1.0.0
  build: ^2.0.0
  meta: ^1.0.0
  source_gen: ^1.0.0
  
  # Annotations for EnigmaUI.
  enigma_annotation: 0.1.0

dependency_overrides:
  enigma_annotation:
    path: ../enigma_annotation