name: enigma_serializable
repository: https://github.com/gedzeppelin/enigma_dart
description: Automatically generate code for EnigmaUI conventions by annotating Dart classes.
version: 0.0.1
#author: Gedy Palomino <gedy.palomino@gmail.com>

environment:  
  sdk: ">=2.0.0 <3.0.0" 

dependencies:  
  analyzer: ">=0.41.2 <1.0.0"
  build: ">=1.5.2 <2.0.0"
  meta: ">=1.2.4 <2.0.0"
  source_gen: ">=0.9.10+1 <1.0.0"
  
  # Annotations for EnigmaUI.
  enigma_annotation: ">=0.0.1 <0.0.2"

#dependency_overrides:
#  enigma_annotation:
#    path: ../enigma_annotation